/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  ForgotRequest,
  ResetRequest,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    ForgotRequestFromJSON,
    ForgotRequestToJSON,
    ResetRequestFromJSON,
    ResetRequestToJSON,
} from '../models/index';

export interface ForgotOperationRequest {
    forgotRequest: ForgotRequest;
}

export interface ResetOperationRequest {
    resetRequest: ResetRequest;
}

/**
 * 
 */
export class AuthPasswordApi extends runtime.BaseAPI {

    /**
     * Creates request options for forgot without sending the request
     */
    async forgotRequestOpts(requestParameters: ForgotOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['forgotRequest'] == null) {
            throw new runtime.RequiredError(
                'forgotRequest',
                'Required parameter "forgotRequest" was null or undefined when calling forgot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/password/forgot`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForgotRequestToJSON(requestParameters['forgotRequest']),
        };
    }

    /**
     */
    async forgotRaw(requestParameters: ForgotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.forgotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async forgot(requestParameters: ForgotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.forgotRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for reset without sending the request
     */
    async resetRequestOpts(requestParameters: ResetOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resetRequest'] == null) {
            throw new runtime.RequiredError(
                'resetRequest',
                'Required parameter "resetRequest" was null or undefined when calling reset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/password/reset`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetRequestToJSON(requestParameters['resetRequest']),
        };
    }

    /**
     */
    async resetRaw(requestParameters: ResetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.resetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async reset(requestParameters: ResetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resetRaw(requestParameters, initOverrides);
    }

}
