/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  DraftResponse,
  PayRequest,
  ReserveRequest,
  StartPaymentResponse,
  SubmitResponse,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    DraftResponseFromJSON,
    DraftResponseToJSON,
    PayRequestFromJSON,
    PayRequestToJSON,
    ReserveRequestFromJSON,
    ReserveRequestToJSON,
    StartPaymentResponseFromJSON,
    StartPaymentResponseToJSON,
    SubmitResponseFromJSON,
    SubmitResponseToJSON,
} from '../models/index';

export interface CancelRequest {
    draftId: string;
}

export interface GetDraftRequest {
    draftId: string;
}

export interface PayOperationRequest {
    draftId: string;
    payRequest: PayRequest;
    idempotencyKey?: string;
}

export interface Reserve1Request {
    reserveRequest?: ReserveRequest;
}

export interface SubmitRequest {
    draftId: string;
}

/**
 * 
 */
export class CheckoutApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancel without sending the request
     */
    async cancelRequestOpts(requestParameters: CancelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftId'] == null) {
            throw new runtime.RequiredError(
                'draftId',
                'Required parameter "draftId" was null or undefined when calling cancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/checkout/drafts/{draftId}/cancel`;
        urlPath = urlPath.replace(`{${"draftId"}}`, encodeURIComponent(String(requestParameters['draftId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async cancelRaw(requestParameters: CancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cancel(requestParameters: CancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getDraft without sending the request
     */
    async getDraftRequestOpts(requestParameters: GetDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftId'] == null) {
            throw new runtime.RequiredError(
                'draftId',
                'Required parameter "draftId" was null or undefined when calling getDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/checkout/drafts/{draftId}`;
        urlPath = urlPath.replace(`{${"draftId"}}`, encodeURIComponent(String(requestParameters['draftId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getDraftRaw(requestParameters: GetDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DraftResponse>> {
        const requestOptions = await this.getDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DraftResponseFromJSON(jsonValue));
    }

    /**
     */
    async getDraft(requestParameters: GetDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DraftResponse> {
        const response = await this.getDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pay without sending the request
     */
    async payRequestOpts(requestParameters: PayOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftId'] == null) {
            throw new runtime.RequiredError(
                'draftId',
                'Required parameter "draftId" was null or undefined when calling pay().'
            );
        }

        if (requestParameters['payRequest'] == null) {
            throw new runtime.RequiredError(
                'payRequest',
                'Required parameter "payRequest" was null or undefined when calling pay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/checkout/drafts/{draftId}/pay`;
        urlPath = urlPath.replace(`{${"draftId"}}`, encodeURIComponent(String(requestParameters['draftId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayRequestToJSON(requestParameters['payRequest']),
        };
    }

    /**
     * Creates an order in PENDING_PAYMENT, snapshots shipping address and creates payment intent. Supports Idempotency-Key header.
     * Start payment for a draft
     */
    async payRaw(requestParameters: PayOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartPaymentResponse>> {
        const requestOptions = await this.payRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartPaymentResponseFromJSON(jsonValue));
    }

    /**
     * Creates an order in PENDING_PAYMENT, snapshots shipping address and creates payment intent. Supports Idempotency-Key header.
     * Start payment for a draft
     */
    async pay(requestParameters: PayOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartPaymentResponse> {
        const response = await this.payRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reserve1 without sending the request
     */
    async reserve1RequestOpts(requestParameters: Reserve1Request): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/checkout/reserve`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReserveRequestToJSON(requestParameters['reserveRequest']),
        };
    }

    /**
     */
    async reserve1Raw(requestParameters: Reserve1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DraftResponse>> {
        const requestOptions = await this.reserve1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DraftResponseFromJSON(jsonValue));
    }

    /**
     */
    async reserve1(requestParameters: Reserve1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DraftResponse> {
        const response = await this.reserve1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submit without sending the request
     */
    async submitRequestOpts(requestParameters: SubmitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftId'] == null) {
            throw new runtime.RequiredError(
                'draftId',
                'Required parameter "draftId" was null or undefined when calling submit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/checkout/drafts/{draftId}/submit`;
        urlPath = urlPath.replace(`{${"draftId"}}`, encodeURIComponent(String(requestParameters['draftId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async submitRaw(requestParameters: SubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitResponse>> {
        const requestOptions = await this.submitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmitResponseFromJSON(jsonValue));
    }

    /**
     */
    async submit(requestParameters: SubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitResponse> {
        const response = await this.submitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
