/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  ApiRoot,
  ApiStatus,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    ApiRootFromJSON,
    ApiRootToJSON,
    ApiStatusFromJSON,
    ApiStatusToJSON,
} from '../models/index';

/**
 * 
 */
export class HomeControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiRoot without sending the request
     */
    async apiRootRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRootRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRootRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRootRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRoot1 without sending the request
     */
    async apiRoot1RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRoot1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRoot1RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRoot1Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRoot2 without sending the request
     */
    async apiRoot2RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRoot2Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRoot2RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot2(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRoot2Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRoot3 without sending the request
     */
    async apiRoot3RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRoot3Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRoot3RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot3(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRoot3Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRoot4 without sending the request
     */
    async apiRoot4RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRoot4Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRoot4RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot4(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRoot4Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRoot5 without sending the request
     */
    async apiRoot5RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRoot5Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRoot5RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot5(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRoot5Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRoot6 without sending the request
     */
    async apiRoot6RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1`;

        return {
            path: urlPath,
            method: 'OPTIONS',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiRoot6Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRoot>> {
        const requestOptions = await this.apiRoot6RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRootFromJSON(jsonValue));
    }

    /**
     */
    async apiRoot6(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRoot> {
        const response = await this.apiRoot6Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for status without sending the request
     */
    async statusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async statusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiStatus>> {
        const requestOptions = await this.statusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiStatusFromJSON(jsonValue));
    }

    /**
     */
    async status(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiStatus> {
        const response = await this.statusRaw(initOverrides);
        return await response.value();
    }

}
