/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  ReservationResponse,
  ReserveRequest,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    ReservationResponseFromJSON,
    ReservationResponseToJSON,
    ReserveRequestFromJSON,
    ReserveRequestToJSON,
} from '../models/index';

export interface ConsumeRequest {
    reservationId: string;
}

export interface ReleaseRequest {
    reservationId: string;
}

export interface ReserveOperationRequest {
    reserveRequest: ReserveRequest;
}

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for consume without sending the request
     */
    async consumeRequestOpts(requestParameters: ConsumeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling consume().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/inventory/reservations/{reservationId}/consume`;
        urlPath = urlPath.replace(`{${"reservationId"}}`, encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async consumeRaw(requestParameters: ConsumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.consumeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async consume(requestParameters: ConsumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.consumeRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for release without sending the request
     */
    async releaseRequestOpts(requestParameters: ReleaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling release().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/inventory/reservations/{reservationId}/release`;
        urlPath = urlPath.replace(`{${"reservationId"}}`, encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async releaseRaw(requestParameters: ReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.releaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async release(requestParameters: ReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.releaseRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for reserve without sending the request
     */
    async reserveRequestOpts(requestParameters: ReserveOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reserveRequest'] == null) {
            throw new runtime.RequiredError(
                'reserveRequest',
                'Required parameter "reserveRequest" was null or undefined when calling reserve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/inventory/reserve`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReserveRequestToJSON(requestParameters['reserveRequest']),
        };
    }

    /**
     */
    async reserveRaw(requestParameters: ReserveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationResponse>> {
        const requestOptions = await this.reserveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationResponseFromJSON(jsonValue));
    }

    /**
     */
    async reserve(requestParameters: ReserveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationResponse> {
        const response = await this.reserveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
