/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  OrderDetailResponse,
  PageResponse,
  RefundRequest,
  RefundResponse,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    OrderDetailResponseFromJSON,
    OrderDetailResponseToJSON,
    PageResponseFromJSON,
    PageResponseToJSON,
    RefundRequestFromJSON,
    RefundRequestToJSON,
    RefundResponseFromJSON,
    RefundResponseToJSON,
} from '../models/index';

export interface Get2Request {
    orderId: string;
}

export interface List4Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface RefundOperationRequest {
    orderId: string;
    refundRequest?: RefundRequest;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for get2 without sending the request
     */
    async get2RequestOpts(requestParameters: Get2Request): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling get2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get my order details
     */
    async get2Raw(requestParameters: Get2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetailResponse>> {
        const requestOptions = await this.get2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get my order details
     */
    async get2(requestParameters: Get2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetailResponse> {
        const response = await this.get2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for list4 without sending the request
     */
    async list4RequestOpts(requestParameters: List4Request): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the authenticated user\'s orders (newest first).
     * List my orders
     */
    async list4Raw(requestParameters: List4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponse>> {
        const requestOptions = await this.list4RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponseFromJSON(jsonValue));
    }

    /**
     * Returns the authenticated user\'s orders (newest first).
     * List my orders
     */
    async list4(requestParameters: List4Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponse> {
        const response = await this.list4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refund without sending the request
     */
    async refundRequestOpts(requestParameters: RefundOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling refund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/orders/{orderId}/refund`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefundRequestToJSON(requestParameters['refundRequest']),
        };
    }

    /**
     */
    async refundRaw(requestParameters: RefundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefundResponse>> {
        const requestOptions = await this.refundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundResponseFromJSON(jsonValue));
    }

    /**
     */
    async refund(requestParameters: RefundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundResponse> {
        const response = await this.refundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
