/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  FailRequest,
  PaymentResponse,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    FailRequestFromJSON,
    FailRequestToJSON,
    PaymentResponseFromJSON,
    PaymentResponseToJSON,
} from '../models/index';

export interface ConfirmMockRequest {
    paymentId: string;
}

export interface FailMockRequest {
    paymentId: string;
    failRequest?: FailRequest;
}

export interface Get1Request {
    paymentId: string;
}

/**
 * 
 */
export class PaymentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for confirmMock without sending the request
     */
    async confirmMockRequestOpts(requestParameters: ConfirmMockRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling confirmMock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/payments/{paymentId}/confirm-mock`;
        urlPath = urlPath.replace(`{${"paymentId"}}`, encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async confirmMockRaw(requestParameters: ConfirmMockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.confirmMockRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async confirmMock(requestParameters: ConfirmMockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmMockRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for failMock without sending the request
     */
    async failMockRequestOpts(requestParameters: FailMockRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling failMock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/payments/{paymentId}/fail-mock`;
        urlPath = urlPath.replace(`{${"paymentId"}}`, encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FailRequestToJSON(requestParameters['failRequest']),
        };
    }

    /**
     */
    async failMockRaw(requestParameters: FailMockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.failMockRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async failMock(requestParameters: FailMockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.failMockRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for get1 without sending the request
     */
    async get1RequestOpts(requestParameters: Get1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling get1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/payments/{paymentId}`;
        urlPath = urlPath.replace(`{${"paymentId"}}`, encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async get1Raw(requestParameters: Get1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        const requestOptions = await this.get1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     */
    async get1(requestParameters: Get1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.get1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
