/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddImageRequest
 */
export interface AddImageRequest {
    /**
     * 
     * @type {string}
     * @memberof AddImageRequest
     */
    altText?: string;
    /**
     * 
     * @type {string}
     * @memberof AddImageRequest
     */
    url: string;
}

/**
 * Check if a given object implements the AddImageRequest interface.
 */
export function instanceOfAddImageRequest(value: object): value is AddImageRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AddImageRequestFromJSON(json: any): AddImageRequest {
    return AddImageRequestFromJSONTyped(json, false);
}

export function AddImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'altText': json['altText'] == null ? undefined : json['altText'],
        'url': json['url'],
    };
}

export function AddImageRequestToJSON(json: any): AddImageRequest {
    return AddImageRequestToJSONTyped(json, false);
}

export function AddImageRequestToJSONTyped(value?: AddImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'altText': value['altText'],
        'url': value['url'],
    };
}

