/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressResponse
 */
export interface AddressResponse {
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    countryCode?: string;
    /**
     * 
     * @type {Date}
     * @memberof AddressResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    fullName?: string;
    /**
     * 
     * @type {number}
     * @memberof AddressResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof AddressResponse
     */
    isDefault?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    state?: string;
    /**
     * 
     * @type {Date}
     * @memberof AddressResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the AddressResponse interface.
 */
export function instanceOfAddressResponse(value: object): value is AddressResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AddressResponseFromJSON(json: any): AddressResponse {
    return AddressResponseFromJSONTyped(json, false);
}

export function AddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'id': json['id'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'label': json['label'] == null ? undefined : json['label'],
        'line1': json['line1'] == null ? undefined : json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'state': json['state'] == null ? undefined : json['state'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AddressResponseToJSON(json: any): AddressResponse {
    return AddressResponseToJSONTyped(json, false);
}

export function AddressResponseToJSONTyped(value?: AddressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'countryCode': value['countryCode'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'fullName': value['fullName'],
        'id': value['id'],
        'isDefault': value['isDefault'],
        'label': value['label'],
        'line1': value['line1'],
        'line2': value['line2'],
        'phone': value['phone'],
        'postalCode': value['postalCode'],
        'state': value['state'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

