/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiProblemViolationsInner } from './ApiProblemViolationsInner';
import {
    ApiProblemViolationsInnerFromJSON,
    ApiProblemViolationsInnerFromJSONTyped,
    ApiProblemViolationsInnerToJSON,
    ApiProblemViolationsInnerToJSONTyped,
} from './ApiProblemViolationsInner';

/**
 * 
 * @export
 * @interface ApiProblem
 */
export interface ApiProblem {
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    instance?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    requestId?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiProblem
     */
    retryAfterSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiProblem
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    type?: string;
    /**
     * 
     * @type {Array<ApiProblemViolationsInner>}
     * @memberof ApiProblem
     */
    violations?: Array<ApiProblemViolationsInner>;
}

/**
 * Check if a given object implements the ApiProblem interface.
 */
export function instanceOfApiProblem(value: object): value is ApiProblem {
    return true;
}

export function ApiProblemFromJSON(json: any): ApiProblem {
    return ApiProblemFromJSONTyped(json, false);
}

export function ApiProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProblem {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'retryAfterSeconds': json['retryAfterSeconds'] == null ? undefined : json['retryAfterSeconds'],
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'violations': json['violations'] == null ? undefined : ((json['violations'] as Array<any>).map(ApiProblemViolationsInnerFromJSON)),
    };
}

export function ApiProblemToJSON(json: any): ApiProblem {
    return ApiProblemToJSONTyped(json, false);
}

export function ApiProblemToJSONTyped(value?: ApiProblem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
        'instance': value['instance'],
        'requestId': value['requestId'],
        'retryAfterSeconds': value['retryAfterSeconds'],
        'status': value['status'],
        'timestamp': value['timestamp'],
        'title': value['title'],
        'type': value['type'],
        'violations': value['violations'] == null ? undefined : ((value['violations'] as Array<any>).map(ApiProblemViolationsInnerToJSON)),
    };
}

