/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiProblemViolationsInner
 */
export interface ApiProblemViolationsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiProblemViolationsInner
     */
    field?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiProblemViolationsInner
     */
    invalidValue?: object;
    /**
     * 
     * @type {string}
     * @memberof ApiProblemViolationsInner
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblemViolationsInner
     */
    path?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiProblemViolationsInner
     */
    rejectedValue?: object;
}

/**
 * Check if a given object implements the ApiProblemViolationsInner interface.
 */
export function instanceOfApiProblemViolationsInner(value: object): value is ApiProblemViolationsInner {
    return true;
}

export function ApiProblemViolationsInnerFromJSON(json: any): ApiProblemViolationsInner {
    return ApiProblemViolationsInnerFromJSONTyped(json, false);
}

export function ApiProblemViolationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProblemViolationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'invalidValue': json['invalidValue'] == null ? undefined : json['invalidValue'],
        'message': json['message'] == null ? undefined : json['message'],
        'path': json['path'] == null ? undefined : json['path'],
        'rejectedValue': json['rejectedValue'] == null ? undefined : json['rejectedValue'],
    };
}

export function ApiProblemViolationsInnerToJSON(json: any): ApiProblemViolationsInner {
    return ApiProblemViolationsInnerToJSONTyped(json, false);
}

export function ApiProblemViolationsInnerToJSONTyped(value?: ApiProblemViolationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'invalidValue': value['invalidValue'],
        'message': value['message'],
        'path': value['path'],
        'rejectedValue': value['rejectedValue'],
    };
}

