/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRoot
 */
export interface ApiRoot {
    /**
     * 
     * @type {string}
     * @memberof ApiRoot
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiRoot
     */
    version?: string;
}

/**
 * Check if a given object implements the ApiRoot interface.
 */
export function instanceOfApiRoot(value: object): value is ApiRoot {
    return true;
}

export function ApiRootFromJSON(json: any): ApiRoot {
    return ApiRootFromJSONTyped(json, false);
}

export function ApiRootFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRoot {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ApiRootToJSON(json: any): ApiRoot {
    return ApiRootToJSONTyped(json, false);
}

export function ApiRootToJSONTyped(value?: ApiRoot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'version': value['version'],
    };
}

