/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiStatus
 */
export interface ApiStatus {
    /**
     * 
     * @type {string}
     * @memberof ApiStatus
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiStatus
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiStatus
     */
    time?: Date;
}

/**
 * Check if a given object implements the ApiStatus interface.
 */
export function instanceOfApiStatus(value: object): value is ApiStatus {
    return true;
}

export function ApiStatusFromJSON(json: any): ApiStatus {
    return ApiStatusFromJSONTyped(json, false);
}

export function ApiStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : json['app'],
        'status': json['status'] == null ? undefined : json['status'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
    };
}

export function ApiStatusToJSON(json: any): ApiStatus {
    return ApiStatusToJSONTyped(json, false);
}

export function ApiStatusToJSONTyped(value?: ApiStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'status': value['status'],
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
    };
}

