/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemResponse
 */
export interface CartItemResponse {
    /**
     * 
     * @type {string}
     * @memberof CartItemResponse
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    lineTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof CartItemResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CartItemResponse
     */
    primaryImageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof CartItemResponse
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    unitPrice?: number;
}

/**
 * Check if a given object implements the CartItemResponse interface.
 */
export function instanceOfCartItemResponse(value: object): value is CartItemResponse {
    return true;
}

export function CartItemResponseFromJSON(json: any): CartItemResponse {
    return CartItemResponseFromJSONTyped(json, false);
}

export function CartItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'lineTotal': json['lineTotal'] == null ? undefined : json['lineTotal'],
        'name': json['name'] == null ? undefined : json['name'],
        'primaryImageUrl': json['primaryImageUrl'] == null ? undefined : json['primaryImageUrl'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
    };
}

export function CartItemResponseToJSON(json: any): CartItemResponse {
    return CartItemResponseToJSONTyped(json, false);
}

export function CartItemResponseToJSONTyped(value?: CartItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'lineTotal': value['lineTotal'],
        'name': value['name'],
        'primaryImageUrl': value['primaryImageUrl'],
        'productId': value['productId'],
        'quantity': value['quantity'],
        'sku': value['sku'],
        'unitPrice': value['unitPrice'],
    };
}

