/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartItemResponse } from './CartItemResponse';
import {
    CartItemResponseFromJSON,
    CartItemResponseFromJSONTyped,
    CartItemResponseToJSON,
    CartItemResponseToJSONTyped,
} from './CartItemResponse';

/**
 * 
 * @export
 * @interface CartResponse
 */
export interface CartResponse {
    /**
     * 
     * @type {Array<CartItemResponse>}
     * @memberof CartResponse
     */
    items?: Array<CartItemResponse>;
}

/**
 * Check if a given object implements the CartResponse interface.
 */
export function instanceOfCartResponse(value: object): value is CartResponse {
    return true;
}

export function CartResponseFromJSON(json: any): CartResponse {
    return CartResponseFromJSONTyped(json, false);
}

export function CartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CartItemResponseFromJSON)),
    };
}

export function CartResponseToJSON(json: any): CartResponse {
    return CartResponseToJSONTyped(json, false);
}

export function CartResponseToJSONTyped(value?: CartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CartItemResponseToJSON)),
    };
}

