/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryRef
 */
export interface CategoryRef {
    /**
     * 
     * @type {number}
     * @memberof CategoryRef
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryRef
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryRef
     */
    slug?: string;
}

/**
 * Check if a given object implements the CategoryRef interface.
 */
export function instanceOfCategoryRef(value: object): value is CategoryRef {
    return true;
}

export function CategoryRefFromJSON(json: any): CategoryRef {
    return CategoryRefFromJSONTyped(json, false);
}

export function CategoryRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function CategoryRefToJSON(json: any): CategoryRef {
    return CategoryRefToJSONTyped(json, false);
}

export function CategoryRefToJSONTyped(value?: CategoryRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

