/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAddressRequest
 */
export interface CreateAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    line1: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    line2?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAddressRequest
     */
    makeDefault?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequest
     */
    state?: string;
}

/**
 * Check if a given object implements the CreateAddressRequest interface.
 */
export function instanceOfCreateAddressRequest(value: object): value is CreateAddressRequest {
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('line1' in value) || value['line1'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    return true;
}

export function CreateAddressRequestFromJSON(json: any): CreateAddressRequest {
    return CreateAddressRequestFromJSONTyped(json, false);
}

export function CreateAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAddressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'countryCode': json['countryCode'],
        'fullName': json['fullName'],
        'label': json['label'] == null ? undefined : json['label'],
        'line1': json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'makeDefault': json['makeDefault'] == null ? undefined : json['makeDefault'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCode': json['postalCode'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function CreateAddressRequestToJSON(json: any): CreateAddressRequest {
    return CreateAddressRequestToJSONTyped(json, false);
}

export function CreateAddressRequestToJSONTyped(value?: CreateAddressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'countryCode': value['countryCode'],
        'fullName': value['fullName'],
        'label': value['label'],
        'line1': value['line1'],
        'line2': value['line2'],
        'makeDefault': value['makeDefault'],
        'phone': value['phone'],
        'postalCode': value['postalCode'],
        'state': value['state'],
    };
}

