/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * 
     * @type {Set<number>}
     * @memberof CreateProductRequest
     */
    categoryIds?: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    sku: string;
    /**
     * 
     * @type {CreateProductRequestStatusEnum}
     * @memberof CreateProductRequest
     */
    status: CreateProductRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    stockQuantity?: number;
}


/**
 * @export
 */
export const CreateProductRequestStatusEnum = {
    Draft: 'DRAFT',
    Active: 'ACTIVE',
    Archived: 'ARCHIVED'
} as const;
export type CreateProductRequestStatusEnum = typeof CreateProductRequestStatusEnum[keyof typeof CreateProductRequestStatusEnum];


/**
 * Check if a given object implements the CreateProductRequest interface.
 */
export function instanceOfCreateProductRequest(value: object): value is CreateProductRequest {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateProductRequestFromJSON(json: any): CreateProductRequest {
    return CreateProductRequestFromJSONTyped(json, false);
}

export function CreateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryIds': json['categoryIds'] == null ? undefined : new Set(json['categoryIds']),
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'price': json['price'],
        'sku': json['sku'],
        'status': json['status'],
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
    };
}

export function CreateProductRequestToJSON(json: any): CreateProductRequest {
    return CreateProductRequestToJSONTyped(json, false);
}

export function CreateProductRequestToJSONTyped(value?: CreateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryIds': value['categoryIds'] == null ? undefined : Array.from(value['categoryIds'] as Set<any>),
        'currency': value['currency'],
        'description': value['description'],
        'name': value['name'],
        'price': value['price'],
        'sku': value['sku'],
        'status': value['status'],
        'stockQuantity': value['stockQuantity'],
    };
}

