/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DraftItemResponse } from './DraftItemResponse';
import {
    DraftItemResponseFromJSON,
    DraftItemResponseFromJSONTyped,
    DraftItemResponseToJSON,
    DraftItemResponseToJSONTyped,
} from './DraftItemResponse';

/**
 * 
 * @export
 * @interface DraftResponse
 */
export interface DraftResponse {
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    draftId?: string;
    /**
     * 
     * @type {Date}
     * @memberof DraftResponse
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Array<DraftItemResponse>}
     * @memberof DraftResponse
     */
    items?: Array<DraftItemResponse>;
    /**
     * 
     * @type {DraftResponseStatusEnum}
     * @memberof DraftResponse
     */
    status?: DraftResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof DraftResponse
     */
    totalAmount?: number;
}


/**
 * @export
 */
export const DraftResponseStatusEnum = {
    Draft: 'DRAFT',
    Reserved: 'RESERVED',
    PaymentPending: 'PAYMENT_PENDING',
    Submitted: 'SUBMITTED',
    Cancelled: 'CANCELLED',
    Expired: 'EXPIRED'
} as const;
export type DraftResponseStatusEnum = typeof DraftResponseStatusEnum[keyof typeof DraftResponseStatusEnum];


/**
 * Check if a given object implements the DraftResponse interface.
 */
export function instanceOfDraftResponse(value: object): value is DraftResponse {
    return true;
}

export function DraftResponseFromJSON(json: any): DraftResponse {
    return DraftResponseFromJSONTyped(json, false);
}

export function DraftResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'draftId': json['draftId'] == null ? undefined : json['draftId'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(DraftItemResponseFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
    };
}

export function DraftResponseToJSON(json: any): DraftResponse {
    return DraftResponseToJSONTyped(json, false);
}

export function DraftResponseToJSONTyped(value?: DraftResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'draftId': value['draftId'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(DraftItemResponseToJSON)),
        'status': value['status'],
        'totalAmount': value['totalAmount'],
    };
}

