/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DraftItemResponse
 */
export interface DraftItemResponse {
    /**
     * 
     * @type {string}
     * @memberof DraftItemResponse
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof DraftItemResponse
     */
    lineTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof DraftItemResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DraftItemResponse
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof DraftItemResponse
     */
    quantity?: number;
    /**
     * 
     * @type {Date}
     * @memberof DraftItemResponse
     */
    reservationExpiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof DraftItemResponse
     */
    reservationId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftItemResponse
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof DraftItemResponse
     */
    unitPrice?: number;
}

/**
 * Check if a given object implements the DraftItemResponse interface.
 */
export function instanceOfDraftItemResponse(value: object): value is DraftItemResponse {
    return true;
}

export function DraftItemResponseFromJSON(json: any): DraftItemResponse {
    return DraftItemResponseFromJSONTyped(json, false);
}

export function DraftItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'lineTotal': json['lineTotal'] == null ? undefined : json['lineTotal'],
        'name': json['name'] == null ? undefined : json['name'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'reservationExpiresAt': json['reservationExpiresAt'] == null ? undefined : (new Date(json['reservationExpiresAt'])),
        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
    };
}

export function DraftItemResponseToJSON(json: any): DraftItemResponse {
    return DraftItemResponseToJSONTyped(json, false);
}

export function DraftItemResponseToJSONTyped(value?: DraftItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'lineTotal': value['lineTotal'],
        'name': value['name'],
        'productId': value['productId'],
        'quantity': value['quantity'],
        'reservationExpiresAt': value['reservationExpiresAt'] == null ? value['reservationExpiresAt'] : value['reservationExpiresAt'].toISOString(),
        'reservationId': value['reservationId'],
        'sku': value['sku'],
        'unitPrice': value['unitPrice'],
    };
}

