/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FailRequest
 */
export interface FailRequest {
    /**
     * 
     * @type {string}
     * @memberof FailRequest
     */
    error?: string;
}

/**
 * Check if a given object implements the FailRequest interface.
 */
export function instanceOfFailRequest(value: object): value is FailRequest {
    return true;
}

export function FailRequestFromJSON(json: any): FailRequest {
    return FailRequestFromJSONTyped(json, false);
}

export function FailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FailRequestToJSON(json: any): FailRequest {
    return FailRequestToJSONTyped(json, false);
}

export function FailRequestToJSONTyped(value?: FailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

