/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotRequest
 */
export interface ForgotRequest {
    /**
     * 
     * @type {string}
     * @memberof ForgotRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ForgotRequest interface.
 */
export function instanceOfForgotRequest(value: object): value is ForgotRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ForgotRequestFromJSON(json: any): ForgotRequest {
    return ForgotRequestFromJSONTyped(json, false);
}

export function ForgotRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ForgotRequestToJSON(json: any): ForgotRequest {
    return ForgotRequestToJSONTyped(json, false);
}

export function ForgotRequestToJSONTyped(value?: ForgotRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

