/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagePageItem
 */
export interface ImagePageItem {
    /**
     * 
     * @type {string}
     * @memberof ImagePageItem
     */
    altText?: string;
    /**
     * 
     * @type {Date}
     * @memberof ImagePageItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof ImagePageItem
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ImagePageItem
     */
    primary?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ImagePageItem
     */
    sortOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof ImagePageItem
     */
    url?: string;
}

/**
 * Check if a given object implements the ImagePageItem interface.
 */
export function instanceOfImagePageItem(value: object): value is ImagePageItem {
    return true;
}

export function ImagePageItemFromJSON(json: any): ImagePageItem {
    return ImagePageItemFromJSONTyped(json, false);
}

export function ImagePageItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagePageItem {
    if (json == null) {
        return json;
    }
    return {
        
        'altText': json['altText'] == null ? undefined : json['altText'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ImagePageItemToJSON(json: any): ImagePageItem {
    return ImagePageItemToJSONTyped(json, false);
}

export function ImagePageItemToJSONTyped(value?: ImagePageItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'altText': value['altText'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'id': value['id'],
        'primary': value['primary'],
        'sortOrder': value['sortOrder'],
        'url': value['url'],
    };
}

