/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageRef
 */
export interface ImageRef {
    /**
     * 
     * @type {string}
     * @memberof ImageRef
     */
    altText?: string;
    /**
     * 
     * @type {number}
     * @memberof ImageRef
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ImageRef
     */
    primary?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ImageRef
     */
    sortOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof ImageRef
     */
    url?: string;
}

/**
 * Check if a given object implements the ImageRef interface.
 */
export function instanceOfImageRef(value: object): value is ImageRef {
    return true;
}

export function ImageRefFromJSON(json: any): ImageRef {
    return ImageRefFromJSONTyped(json, false);
}

export function ImageRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageRef {
    if (json == null) {
        return json;
    }
    return {
        
        'altText': json['altText'] == null ? undefined : json['altText'],
        'id': json['id'] == null ? undefined : json['id'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ImageRefToJSON(json: any): ImageRef {
    return ImageRefToJSONTyped(json, false);
}

export function ImageRefToJSONTyped(value?: ImageRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'altText': value['altText'],
        'id': value['id'],
        'primary': value['primary'],
        'sortOrder': value['sortOrder'],
        'url': value['url'],
    };
}

