/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeResponse
 */
export interface MeResponse {
    /**
     * 
     * @type {Date}
     * @memberof MeResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MeResponse
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MeResponse
     */
    locked?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeResponse
     */
    roles?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof MeResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the MeResponse interface.
 */
export function instanceOfMeResponse(value: object): value is MeResponse {
    return true;
}

export function MeResponseFromJSON(json: any): MeResponse {
    return MeResponseFromJSONTyped(json, false);
}

export function MeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'email': json['email'] == null ? undefined : json['email'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'locked': json['locked'] == null ? undefined : json['locked'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function MeResponseToJSON(json: any): MeResponse {
    return MeResponseToJSONTyped(json, false);
}

export function MeResponseToJSONTyped(value?: MeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'email': value['email'],
        'enabled': value['enabled'],
        'locked': value['locked'],
        'roles': value['roles'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

