/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderSummaryResponse
 */
export interface OrderSummaryResponse {
    /**
     * 
     * @type {Date}
     * @memberof OrderSummaryResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderSummaryResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderSummaryResponse
     */
    orderId?: string;
    /**
     * Order status lifecycle
     * @type {OrderSummaryResponseStatusEnum}
     * @memberof OrderSummaryResponse
     */
    status?: OrderSummaryResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof OrderSummaryResponse
     */
    totalAmount?: number;
}


/**
 * @export
 */
export const OrderSummaryResponseStatusEnum = {
    PendingPayment: 'PENDING_PAYMENT',
    Paid: 'PAID',
    Shipped: 'SHIPPED',
    PaymentFailed: 'PAYMENT_FAILED',
    RefundPending: 'REFUND_PENDING',
    Refunded: 'REFUNDED',
    Placed: 'PLACED',
    Cancelled: 'CANCELLED',
    Fulfilled: 'FULFILLED'
} as const;
export type OrderSummaryResponseStatusEnum = typeof OrderSummaryResponseStatusEnum[keyof typeof OrderSummaryResponseStatusEnum];


/**
 * Check if a given object implements the OrderSummaryResponse interface.
 */
export function instanceOfOrderSummaryResponse(value: object): value is OrderSummaryResponse {
    return true;
}

export function OrderSummaryResponseFromJSON(json: any): OrderSummaryResponse {
    return OrderSummaryResponseFromJSONTyped(json, false);
}

export function OrderSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
    };
}

export function OrderSummaryResponseToJSON(json: any): OrderSummaryResponse {
    return OrderSummaryResponseToJSONTyped(json, false);
}

export function OrderSummaryResponseToJSONTyped(value?: OrderSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'currency': value['currency'],
        'orderId': value['orderId'],
        'status': value['status'],
        'totalAmount': value['totalAmount'],
    };
}

