/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItemResponse } from './OrderItemResponse';
import {
    OrderItemResponseFromJSON,
    OrderItemResponseFromJSONTyped,
    OrderItemResponseToJSON,
    OrderItemResponseToJSONTyped,
} from './OrderItemResponse';
import type { ShipmentInfo } from './ShipmentInfo';
import {
    ShipmentInfoFromJSON,
    ShipmentInfoFromJSONTyped,
    ShipmentInfoToJSON,
    ShipmentInfoToJSONTyped,
} from './ShipmentInfo';
import type { ShippingAddressInfo } from './ShippingAddressInfo';
import {
    ShippingAddressInfoFromJSON,
    ShippingAddressInfoFromJSONTyped,
    ShippingAddressInfoToJSON,
    ShippingAddressInfoToJSONTyped,
} from './ShippingAddressInfo';

/**
 * 
 * @export
 * @interface OrderDetailResponse
 */
export interface OrderDetailResponse {
    /**
     * 
     * @type {Date}
     * @memberof OrderDetailResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailResponse
     */
    currency?: string;
    /**
     * 
     * @type {Array<OrderItemResponse>}
     * @memberof OrderDetailResponse
     */
    items?: Array<OrderItemResponse>;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailResponse
     */
    orderId?: string;
    /**
     * 
     * @type {Array<ShipmentInfo>}
     * @memberof OrderDetailResponse
     */
    shipments?: Array<ShipmentInfo>;
    /**
     * 
     * @type {ShippingAddressInfo}
     * @memberof OrderDetailResponse
     */
    shippingAddress?: ShippingAddressInfo;
    /**
     * Order status lifecycle
     * @type {OrderDetailResponseStatusEnum}
     * @memberof OrderDetailResponse
     */
    status?: OrderDetailResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof OrderDetailResponse
     */
    totalAmount?: number;
}


/**
 * @export
 */
export const OrderDetailResponseStatusEnum = {
    PendingPayment: 'PENDING_PAYMENT',
    Paid: 'PAID',
    Shipped: 'SHIPPED',
    PaymentFailed: 'PAYMENT_FAILED',
    RefundPending: 'REFUND_PENDING',
    Refunded: 'REFUNDED',
    Placed: 'PLACED',
    Cancelled: 'CANCELLED',
    Fulfilled: 'FULFILLED'
} as const;
export type OrderDetailResponseStatusEnum = typeof OrderDetailResponseStatusEnum[keyof typeof OrderDetailResponseStatusEnum];


/**
 * Check if a given object implements the OrderDetailResponse interface.
 */
export function instanceOfOrderDetailResponse(value: object): value is OrderDetailResponse {
    return true;
}

export function OrderDetailResponseFromJSON(json: any): OrderDetailResponse {
    return OrderDetailResponseFromJSONTyped(json, false);
}

export function OrderDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(OrderItemResponseFromJSON)),
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'shipments': json['shipments'] == null ? undefined : ((json['shipments'] as Array<any>).map(ShipmentInfoFromJSON)),
        'shippingAddress': json['shippingAddress'] == null ? undefined : ShippingAddressInfoFromJSON(json['shippingAddress']),
        'status': json['status'] == null ? undefined : json['status'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
    };
}

export function OrderDetailResponseToJSON(json: any): OrderDetailResponse {
    return OrderDetailResponseToJSONTyped(json, false);
}

export function OrderDetailResponseToJSONTyped(value?: OrderDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'currency': value['currency'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(OrderItemResponseToJSON)),
        'orderId': value['orderId'],
        'shipments': value['shipments'] == null ? undefined : ((value['shipments'] as Array<any>).map(ShipmentInfoToJSON)),
        'shippingAddress': ShippingAddressInfoToJSON(value['shippingAddress']),
        'status': value['status'],
        'totalAmount': value['totalAmount'],
    };
}

