/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageMeta
 */
export interface PageMeta {
    /**
     * 
     * @type {boolean}
     * @memberof PageMeta
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageMeta
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageMeta interface.
 */
export function instanceOfPageMeta(value: object): value is PageMeta {
    return true;
}

export function PageMetaFromJSON(json: any): PageMeta {
    return PageMetaFromJSONTyped(json, false);
}

export function PageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'number': json['number'] == null ? undefined : json['number'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageMetaToJSON(json: any): PageMeta {
    return PageMetaToJSONTyped(json, false);
}

export function PageMetaToJSONTyped(value?: PageMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'last': value['last'],
        'number': value['number'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

