/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * 
     * @type {number}
     * @memberof PaymentResponse
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof PaymentResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    paymentId?: string;
    /**
     * 
     * @type {PaymentResponseProviderEnum}
     * @memberof PaymentResponse
     */
    provider?: PaymentResponseProviderEnum;
    /**
     * Payment intent status
     * @type {PaymentResponseStatusEnum}
     * @memberof PaymentResponse
     */
    status?: PaymentResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof PaymentResponse
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const PaymentResponseProviderEnum = {
    Mock: 'MOCK'
} as const;
export type PaymentResponseProviderEnum = typeof PaymentResponseProviderEnum[keyof typeof PaymentResponseProviderEnum];

/**
 * @export
 */
export const PaymentResponseStatusEnum = {
    RequiresConfirmation: 'REQUIRES_CONFIRMATION',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED',
    Expired: 'EXPIRED',
    Cancelled: 'CANCELLED'
} as const;
export type PaymentResponseStatusEnum = typeof PaymentResponseStatusEnum[keyof typeof PaymentResponseStatusEnum];


/**
 * Check if a given object implements the PaymentResponse interface.
 */
export function instanceOfPaymentResponse(value: object): value is PaymentResponse {
    return true;
}

export function PaymentResponseFromJSON(json: any): PaymentResponse {
    return PaymentResponseFromJSONTyped(json, false);
}

export function PaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PaymentResponseToJSON(json: any): PaymentResponse {
    return PaymentResponseToJSONTyped(json, false);
}

export function PaymentResponseToJSONTyped(value?: PaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'currency': value['currency'],
        'orderId': value['orderId'],
        'paymentId': value['paymentId'],
        'provider': value['provider'],
        'status': value['status'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

