/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayRequest
 */
export interface PayRequest {
    /**
     * Shipping address id
     * @type {number}
     * @memberof PayRequest
     */
    addressId: number;
    /**
     * Card holder full name
     * @type {string}
     * @memberof PayRequest
     */
    cardHolderName?: string;
    /**
     * Card number digits (can include spaces/hyphens)
     * @type {string}
     * @memberof PayRequest
     */
    cardNumber?: string;
    /**
     * Card security code
     * @type {string}
     * @memberof PayRequest
     */
    cvc?: string;
    /**
     * Card expiration month (1-12)
     * @type {number}
     * @memberof PayRequest
     */
    expiryMonth?: number;
    /**
     * Card expiration year (YYYY)
     * @type {number}
     * @memberof PayRequest
     */
    expiryYear?: number;
}

/**
 * Check if a given object implements the PayRequest interface.
 */
export function instanceOfPayRequest(value: object): value is PayRequest {
    if (!('addressId' in value) || value['addressId'] === undefined) return false;
    return true;
}

export function PayRequestFromJSON(json: any): PayRequest {
    return PayRequestFromJSONTyped(json, false);
}

export function PayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addressId': json['addressId'],
        'cardHolderName': json['cardHolderName'] == null ? undefined : json['cardHolderName'],
        'cardNumber': json['cardNumber'] == null ? undefined : json['cardNumber'],
        'cvc': json['cvc'] == null ? undefined : json['cvc'],
        'expiryMonth': json['expiryMonth'] == null ? undefined : json['expiryMonth'],
        'expiryYear': json['expiryYear'] == null ? undefined : json['expiryYear'],
    };
}

export function PayRequestToJSON(json: any): PayRequest {
    return PayRequestToJSONTyped(json, false);
}

export function PayRequestToJSONTyped(value?: PayRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressId': value['addressId'],
        'cardHolderName': value['cardHolderName'],
        'cardNumber': value['cardNumber'],
        'cvc': value['cvc'],
        'expiryMonth': value['expiryMonth'],
        'expiryYear': value['expiryYear'],
    };
}

