/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayRequest
 */
export interface PayRequest {
    /**
     * Shipping address id
     * @type {number}
     * @memberof PayRequest
     */
    addressId: number;
}

/**
 * Check if a given object implements the PayRequest interface.
 */
export function instanceOfPayRequest(value: object): value is PayRequest {
    if (!('addressId' in value) || value['addressId'] === undefined) return false;
    return true;
}

export function PayRequestFromJSON(json: any): PayRequest {
    return PayRequestFromJSONTyped(json, false);
}

export function PayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addressId': json['addressId'],
    };
}

export function PayRequestToJSON(json: any): PayRequest {
    return PayRequestToJSONTyped(json, false);
}

export function PayRequestToJSONTyped(value?: PayRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressId': value['addressId'],
    };
}

