/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageRef } from './ImageRef';
import {
    ImageRefFromJSON,
    ImageRefFromJSONTyped,
    ImageRefToJSON,
    ImageRefToJSONTyped,
} from './ImageRef';
import type { CategoryRef } from './CategoryRef';
import {
    CategoryRefFromJSON,
    CategoryRefFromJSONTyped,
    CategoryRefToJSON,
    CategoryRefToJSONTyped,
} from './CategoryRef';

/**
 * 
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     * 
     * @type {Array<CategoryRef>}
     * @memberof ProductResponse
     */
    categories?: Array<CategoryRef>;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    id?: number;
    /**
     * 
     * @type {Array<ImageRef>}
     * @memberof ProductResponse
     */
    images?: Array<ImageRef>;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    price?: number;
    /**
     * 
     * @type {ImageRef}
     * @memberof ProductResponse
     */
    primaryImage?: ImageRef;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    sku?: string;
    /**
     * 
     * @type {ProductResponseStatusEnum}
     * @memberof ProductResponse
     */
    status?: ProductResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    stockQuantity?: number;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponse
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const ProductResponseStatusEnum = {
    Draft: 'DRAFT',
    Active: 'ACTIVE',
    Archived: 'ARCHIVED'
} as const;
export type ProductResponseStatusEnum = typeof ProductResponseStatusEnum[keyof typeof ProductResponseStatusEnum];


/**
 * Check if a given object implements the ProductResponse interface.
 */
export function instanceOfProductResponse(value: object): value is ProductResponse {
    return true;
}

export function ProductResponseFromJSON(json: any): ProductResponse {
    return ProductResponseFromJSONTyped(json, false);
}

export function ProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryRefFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageRefFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'primaryImage': json['primaryImage'] == null ? undefined : ImageRefFromJSON(json['primaryImage']),
        'sku': json['sku'] == null ? undefined : json['sku'],
        'status': json['status'] == null ? undefined : json['status'],
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ProductResponseToJSON(json: any): ProductResponse {
    return ProductResponseToJSONTyped(json, false);
}

export function ProductResponseToJSONTyped(value?: ProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryRefToJSON)),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'currency': value['currency'],
        'description': value['description'],
        'id': value['id'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageRefToJSON)),
        'name': value['name'],
        'price': value['price'],
        'primaryImage': ImageRefToJSON(value['primaryImage']),
        'sku': value['sku'],
        'status': value['status'],
        'stockQuantity': value['stockQuantity'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

