/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the RefundRequest interface.
 */
export function instanceOfRefundRequest(value: object): value is RefundRequest {
    return true;
}

export function RefundRequestFromJSON(json: any): RefundRequest {
    return RefundRequestFromJSONTyped(json, false);
}

export function RefundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function RefundRequestToJSON(json: any): RefundRequest {
    return RefundRequestToJSONTyped(json, false);
}

export function RefundRequestToJSONTyped(value?: RefundRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

