/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefundResponse
 */
export interface RefundResponse {
    /**
     * 
     * @type {string}
     * @memberof RefundResponse
     */
    refundId?: string;
}

/**
 * Check if a given object implements the RefundResponse interface.
 */
export function instanceOfRefundResponse(value: object): value is RefundResponse {
    return true;
}

export function RefundResponseFromJSON(json: any): RefundResponse {
    return RefundResponseFromJSONTyped(json, false);
}

export function RefundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'refundId': json['refundId'] == null ? undefined : json['refundId'],
    };
}

export function RefundResponseToJSON(json: any): RefundResponse {
    return RefundResponseToJSONTyped(json, false);
}

export function RefundResponseToJSONTyped(value?: RefundResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refundId': value['refundId'],
    };
}

