/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameRequest
 */
export interface RenameRequest {
    /**
     * 
     * @type {string}
     * @memberof RenameRequest
     */
    deviceName?: string;
}

/**
 * Check if a given object implements the RenameRequest interface.
 */
export function instanceOfRenameRequest(value: object): value is RenameRequest {
    return true;
}

export function RenameRequestFromJSON(json: any): RenameRequest {
    return RenameRequestFromJSONTyped(json, false);
}

export function RenameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
    };
}

export function RenameRequestToJSON(json: any): RenameRequest {
    return RenameRequestToJSONTyped(json, false);
}

export function RenameRequestToJSONTyped(value?: RenameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
    };
}

