/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReorderItem } from './ReorderItem';
import {
    ReorderItemFromJSON,
    ReorderItemFromJSONTyped,
    ReorderItemToJSON,
    ReorderItemToJSONTyped,
} from './ReorderItem';

/**
 * 
 * @export
 * @interface ReorderRequest
 */
export interface ReorderRequest {
    /**
     * 
     * @type {Array<ReorderItem>}
     * @memberof ReorderRequest
     */
    items: Array<ReorderItem>;
}

/**
 * Check if a given object implements the ReorderRequest interface.
 */
export function instanceOfReorderRequest(value: object): value is ReorderRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ReorderRequestFromJSON(json: any): ReorderRequest {
    return ReorderRequestFromJSONTyped(json, false);
}

export function ReorderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ReorderItemFromJSON)),
    };
}

export function ReorderRequestToJSON(json: any): ReorderRequest {
    return ReorderRequestToJSONTyped(json, false);
}

export function ReorderRequestToJSONTyped(value?: ReorderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ReorderItemToJSON)),
    };
}

