/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReorderItem
 */
export interface ReorderItem {
    /**
     * 
     * @type {number}
     * @memberof ReorderItem
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReorderItem
     */
    primary?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ReorderItem
     */
    sortOrder?: number;
}

/**
 * Check if a given object implements the ReorderItem interface.
 */
export function instanceOfReorderItem(value: object): value is ReorderItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ReorderItemFromJSON(json: any): ReorderItem {
    return ReorderItemFromJSONTyped(json, false);
}

export function ReorderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
    };
}

export function ReorderItemToJSON(json: any): ReorderItem {
    return ReorderItemToJSONTyped(json, false);
}

export function ReorderItemToJSONTyped(value?: ReorderItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'primary': value['primary'],
        'sortOrder': value['sortOrder'],
    };
}

