/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReserveRequest
 */
export interface ReserveRequest {
    /**
     * 
     * @type {number}
     * @memberof ReserveRequest
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof ReserveRequest
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ReserveRequest
     */
    ttlMinutes?: number;
}

/**
 * Check if a given object implements the ReserveRequest interface.
 */
export function instanceOfReserveRequest(value: object): value is ReserveRequest {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function ReserveRequestFromJSON(json: any): ReserveRequest {
    return ReserveRequestFromJSONTyped(json, false);
}

export function ReserveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReserveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'ttlMinutes': json['ttlMinutes'] == null ? undefined : json['ttlMinutes'],
    };
}

export function ReserveRequestToJSON(json: any): ReserveRequest {
    return ReserveRequestToJSONTyped(json, false);
}

export function ReserveRequestToJSONTyped(value?: ReserveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
        'ttlMinutes': value['ttlMinutes'],
    };
}

