/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReservationResponse
 */
export interface ReservationResponse {
    /**
     * 
     * @type {string}
     * @memberof ReservationResponse
     */
    expiresAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationResponse
     */
    remainingStock?: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationResponse
     */
    reservationId?: string;
}

/**
 * Check if a given object implements the ReservationResponse interface.
 */
export function instanceOfReservationResponse(value: object): value is ReservationResponse {
    return true;
}

export function ReservationResponseFromJSON(json: any): ReservationResponse {
    return ReservationResponseFromJSONTyped(json, false);
}

export function ReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'remainingStock': json['remainingStock'] == null ? undefined : json['remainingStock'],
        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
    };
}

export function ReservationResponseToJSON(json: any): ReservationResponse {
    return ReservationResponseToJSONTyped(json, false);
}

export function ReservationResponseToJSONTyped(value?: ReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiresAt': value['expiresAt'],
        'remainingStock': value['remainingStock'],
        'reservationId': value['reservationId'],
    };
}

