/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetRequest
 */
export interface ResetRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ResetRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ResetRequest interface.
 */
export function instanceOfResetRequest(value: object): value is ResetRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ResetRequestFromJSON(json: any): ResetRequest {
    return ResetRequestFromJSONTyped(json, false);
}

export function ResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['newPassword'],
        'token': json['token'],
    };
}

export function ResetRequestToJSON(json: any): ResetRequest {
    return ResetRequestToJSONTyped(json, false);
}

export function ResetRequestToJSONTyped(value?: ResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newPassword': value['newPassword'],
        'token': value['token'],
    };
}

