/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionDto
 */
export interface SessionDto {
    /**
     * 
     * @type {Date}
     * @memberof SessionDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SessionDto
     */
    current?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    deviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    ip?: string;
    /**
     * 
     * @type {Date}
     * @memberof SessionDto
     */
    lastSeenAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SessionDto
     */
    revoked?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SessionDto
     */
    revokedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    userAgent?: string;
}

/**
 * Check if a given object implements the SessionDto interface.
 */
export function instanceOfSessionDto(value: object): value is SessionDto {
    return true;
}

export function SessionDtoFromJSON(json: any): SessionDto {
    return SessionDtoFromJSONTyped(json, false);
}

export function SessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'current': json['current'] == null ? undefined : json['current'],
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'lastSeenAt': json['lastSeenAt'] == null ? undefined : (new Date(json['lastSeenAt'])),
        'revoked': json['revoked'] == null ? undefined : json['revoked'],
        'revokedAt': json['revokedAt'] == null ? undefined : (new Date(json['revokedAt'])),
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function SessionDtoToJSON(json: any): SessionDto {
    return SessionDtoToJSONTyped(json, false);
}

export function SessionDtoToJSONTyped(value?: SessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'current': value['current'],
        'deviceName': value['deviceName'],
        'ip': value['ip'],
        'lastSeenAt': value['lastSeenAt'] == null ? value['lastSeenAt'] : value['lastSeenAt'].toISOString(),
        'revoked': value['revoked'],
        'revokedAt': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
        'sessionId': value['sessionId'],
        'userAgent': value['userAgent'],
    };
}

