/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipmentInfo
 */
export interface ShipmentInfo {
    /**
     * 
     * @type {string}
     * @memberof ShipmentInfo
     */
    carrier?: string;
    /**
     * 
     * @type {Date}
     * @memberof ShipmentInfo
     */
    deliveredAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShipmentInfo
     */
    shipmentId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ShipmentInfo
     */
    shippedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShipmentInfo
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentInfo
     */
    trackingNumber?: string;
}

/**
 * Check if a given object implements the ShipmentInfo interface.
 */
export function instanceOfShipmentInfo(value: object): value is ShipmentInfo {
    return true;
}

export function ShipmentInfoFromJSON(json: any): ShipmentInfo {
    return ShipmentInfoFromJSONTyped(json, false);
}

export function ShipmentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'carrier': json['carrier'] == null ? undefined : json['carrier'],
        'deliveredAt': json['deliveredAt'] == null ? undefined : (new Date(json['deliveredAt'])),
        'shipmentId': json['shipmentId'] == null ? undefined : json['shipmentId'],
        'shippedAt': json['shippedAt'] == null ? undefined : (new Date(json['shippedAt'])),
        'status': json['status'] == null ? undefined : json['status'],
        'trackingNumber': json['trackingNumber'] == null ? undefined : json['trackingNumber'],
    };
}

export function ShipmentInfoToJSON(json: any): ShipmentInfo {
    return ShipmentInfoToJSONTyped(json, false);
}

export function ShipmentInfoToJSONTyped(value?: ShipmentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrier': value['carrier'],
        'deliveredAt': value['deliveredAt'] == null ? value['deliveredAt'] : value['deliveredAt'].toISOString(),
        'shipmentId': value['shipmentId'],
        'shippedAt': value['shippedAt'] == null ? value['shippedAt'] : value['shippedAt'].toISOString(),
        'status': value['status'],
        'trackingNumber': value['trackingNumber'],
    };
}

