/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingAddressInfo
 */
export interface ShippingAddressInfo {
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingAddressInfo
     */
    state?: string;
}

/**
 * Check if a given object implements the ShippingAddressInfo interface.
 */
export function instanceOfShippingAddressInfo(value: object): value is ShippingAddressInfo {
    return true;
}

export function ShippingAddressInfoFromJSON(json: any): ShippingAddressInfo {
    return ShippingAddressInfoFromJSONTyped(json, false);
}

export function ShippingAddressInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingAddressInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'line1': json['line1'] == null ? undefined : json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function ShippingAddressInfoToJSON(json: any): ShippingAddressInfo {
    return ShippingAddressInfoToJSONTyped(json, false);
}

export function ShippingAddressInfoToJSONTyped(value?: ShippingAddressInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'countryCode': value['countryCode'],
        'fullName': value['fullName'],
        'line1': value['line1'],
        'line2': value['line2'],
        'phone': value['phone'],
        'postalCode': value['postalCode'],
        'state': value['state'],
    };
}

