/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartPaymentResponse
 */
export interface StartPaymentResponse {
    /**
     * 
     * @type {string}
     * @memberof StartPaymentResponse
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof StartPaymentResponse
     */
    paymentId?: string;
}

/**
 * Check if a given object implements the StartPaymentResponse interface.
 */
export function instanceOfStartPaymentResponse(value: object): value is StartPaymentResponse {
    return true;
}

export function StartPaymentResponseFromJSON(json: any): StartPaymentResponse {
    return StartPaymentResponseFromJSONTyped(json, false);
}

export function StartPaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartPaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
    };
}

export function StartPaymentResponseToJSON(json: any): StartPaymentResponse {
    return StartPaymentResponseToJSONTyped(json, false);
}

export function StartPaymentResponseToJSONTyped(value?: StartPaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'paymentId': value['paymentId'],
    };
}

