/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitResponse
 */
export interface SubmitResponse {
    /**
     * 
     * @type {string}
     * @memberof SubmitResponse
     */
    orderId?: string;
}

/**
 * Check if a given object implements the SubmitResponse interface.
 */
export function instanceOfSubmitResponse(value: object): value is SubmitResponse {
    return true;
}

export function SubmitResponseFromJSON(json: any): SubmitResponse {
    return SubmitResponseFromJSONTyped(json, false);
}

export function SubmitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
    };
}

export function SubmitResponseToJSON(json: any): SubmitResponse {
    return SubmitResponseToJSONTyped(json, false);
}

export function SubmitResponseToJSONTyped(value?: SubmitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
    };
}

