/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductRequest
 */
export interface UpdateProductRequest {
    /**
     * 
     * @type {Set<number>}
     * @memberof UpdateProductRequest
     */
    categoryIds?: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    price: number;
    /**
     * 
     * @type {UpdateProductRequestStatusEnum}
     * @memberof UpdateProductRequest
     */
    status: UpdateProductRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    stockQuantity?: number;
}


/**
 * @export
 */
export const UpdateProductRequestStatusEnum = {
    Draft: 'DRAFT',
    Active: 'ACTIVE',
    Archived: 'ARCHIVED'
} as const;
export type UpdateProductRequestStatusEnum = typeof UpdateProductRequestStatusEnum[keyof typeof UpdateProductRequestStatusEnum];


/**
 * Check if a given object implements the UpdateProductRequest interface.
 */
export function instanceOfUpdateProductRequest(value: object): value is UpdateProductRequest {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateProductRequestFromJSON(json: any): UpdateProductRequest {
    return UpdateProductRequestFromJSONTyped(json, false);
}

export function UpdateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryIds': json['categoryIds'] == null ? undefined : new Set(json['categoryIds']),
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'price': json['price'],
        'status': json['status'],
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
    };
}

export function UpdateProductRequestToJSON(json: any): UpdateProductRequest {
    return UpdateProductRequestToJSONTyped(json, false);
}

export function UpdateProductRequestToJSONTyped(value?: UpdateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryIds': value['categoryIds'] == null ? undefined : Array.from(value['categoryIds'] as Set<any>),
        'currency': value['currency'],
        'description': value['description'],
        'name': value['name'],
        'price': value['price'],
        'status': value['status'],
        'stockQuantity': value['stockQuantity'],
    };
}

