/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAddressRequest
 */
export interface UpdateAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    line1: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressRequest
     */
    state?: string;
}

/**
 * Check if a given object implements the UpdateAddressRequest interface.
 */
export function instanceOfUpdateAddressRequest(value: object): value is UpdateAddressRequest {
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('line1' in value) || value['line1'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    return true;
}

export function UpdateAddressRequestFromJSON(json: any): UpdateAddressRequest {
    return UpdateAddressRequestFromJSONTyped(json, false);
}

export function UpdateAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAddressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'countryCode': json['countryCode'],
        'fullName': json['fullName'],
        'label': json['label'] == null ? undefined : json['label'],
        'line1': json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCode': json['postalCode'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function UpdateAddressRequestToJSON(json: any): UpdateAddressRequest {
    return UpdateAddressRequestToJSONTyped(json, false);
}

export function UpdateAddressRequestToJSONTyped(value?: UpdateAddressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'countryCode': value['countryCode'],
        'fullName': value['fullName'],
        'label': value['label'],
        'line1': value['line1'],
        'line2': value['line2'],
        'phone': value['phone'],
        'postalCode': value['postalCode'],
        'state': value['state'],
    };
}

