/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertCartItemRequest
 */
export interface UpsertCartItemRequest {
    /**
     * 
     * @type {number}
     * @memberof UpsertCartItemRequest
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof UpsertCartItemRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the UpsertCartItemRequest interface.
 */
export function instanceOfUpsertCartItemRequest(value: object): value is UpsertCartItemRequest {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function UpsertCartItemRequestFromJSON(json: any): UpsertCartItemRequest {
    return UpsertCartItemRequestFromJSONTyped(json, false);
}

export function UpsertCartItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertCartItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function UpsertCartItemRequestToJSON(json: any): UpsertCartItemRequest {
    return UpsertCartItemRequestToJSONTyped(json, false);
}

export function UpsertCartItemRequestToJSONTyped(value?: UpsertCartItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

