/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminOrderDetail,
  ApiProblem,
  PageResponse,
} from '../models/index';
import {
    AdminOrderDetailFromJSON,
    AdminOrderDetailToJSON,
    ApiProblemFromJSON,
    ApiProblemToJSON,
    PageResponseFromJSON,
    PageResponseToJSON,
} from '../models/index';

export interface GetRequest {
    orderId: string;
}

export interface List2Request {
    status?: List2StatusEnum;
    email?: string;
    q?: string;
    from?: Date;
    to?: Date;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

/**
 * 
 */
export class AdminOrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for get without sending the request
     */
    async getRequestOpts(requestParameters: GetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getRaw(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrderDetail>> {
        const requestOptions = await this.getRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrderDetailFromJSON(jsonValue));
    }

    /**
     */
    async get(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrderDetail> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for list2 without sending the request
     */
    async list2RequestOpts(requestParameters: List2Request): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Filter by status/email/orderId/date range.
     * Admin: list orders
     */
    async list2Raw(requestParameters: List2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponse>> {
        const requestOptions = await this.list2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponseFromJSON(jsonValue));
    }

    /**
     * Filter by status/email/orderId/date range.
     * Admin: list orders
     */
    async list2(requestParameters: List2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponse> {
        const response = await this.list2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const List2StatusEnum = {
    PendingPayment: 'PENDING_PAYMENT',
    Paid: 'PAID',
    Shipped: 'SHIPPED',
    PaymentFailed: 'PAYMENT_FAILED',
    RefundPending: 'REFUND_PENDING',
    Refunded: 'REFUNDED',
    Placed: 'PLACED',
    Cancelled: 'CANCELLED',
    Fulfilled: 'FULFILLED'
} as const;
export type List2StatusEnum = typeof List2StatusEnum[keyof typeof List2StatusEnum];
