/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  PageResponse,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    PageResponseFromJSON,
    PageResponseToJSON,
} from '../models/index';

export interface List1Request {
    status?: List1StatusEnum;
    email?: string;
    orderId?: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

/**
 * 
 */
export class AdminRefundsApi extends runtime.BaseAPI {

    /**
     * Creates request options for list1 without sending the request
     */
    async list1RequestOpts(requestParameters: List1Request): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['orderId'] != null) {
            queryParameters['orderId'] = requestParameters['orderId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/refunds`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Filter by status, user email and order id.
     * Admin: list refunds
     */
    async list1Raw(requestParameters: List1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponse>> {
        const requestOptions = await this.list1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponseFromJSON(jsonValue));
    }

    /**
     * Filter by status, user email and order id.
     * Admin: list refunds
     */
    async list1(requestParameters: List1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponse> {
        const response = await this.list1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const List1StatusEnum = {
    Pending: 'PENDING',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type List1StatusEnum = typeof List1StatusEnum[keyof typeof List1StatusEnum];
