/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProblem,
  CancelRequest,
  ShipRequest,
  ShipmentResponse,
} from '../models/index';
import {
    ApiProblemFromJSON,
    ApiProblemToJSON,
    CancelRequestFromJSON,
    CancelRequestToJSON,
    ShipRequestFromJSON,
    ShipRequestToJSON,
    ShipmentResponseFromJSON,
    ShipmentResponseToJSON,
} from '../models/index';

export interface CancelOperationRequest {
    orderId: string;
    cancelRequest?: CancelRequest;
}

export interface DeliverRequest {
    orderId: string;
}

export interface ShipOperationRequest {
    orderId: string;
    shipRequest: ShipRequest;
}

/**
 * 
 */
export class AdminFulfillmentApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancel without sending the request
     */
    async cancelRequestOpts(requestParameters: CancelOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling cancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/orders/{orderId}/cancel`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelRequestToJSON(requestParameters['cancelRequest']),
        };
    }

    /**
     */
    async cancelRaw(requestParameters: CancelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cancel(requestParameters: CancelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deliver without sending the request
     */
    async deliverRequestOpts(requestParameters: DeliverRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling deliver().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/orders/{orderId}/deliver`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deliverRaw(requestParameters: DeliverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deliverRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deliver(requestParameters: DeliverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deliverRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ship without sending the request
     */
    async shipRequestOpts(requestParameters: ShipOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling ship().'
            );
        }

        if (requestParameters['shipRequest'] == null) {
            throw new runtime.RequiredError(
                'shipRequest',
                'Required parameter "shipRequest" was null or undefined when calling ship().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/orders/{orderId}/ship`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShipRequestToJSON(requestParameters['shipRequest']),
        };
    }

    /**
     */
    async shipRaw(requestParameters: ShipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShipmentResponse>> {
        const requestOptions = await this.shipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShipmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async ship(requestParameters: ShipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShipmentResponse> {
        const response = await this.shipRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
