/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdjustRequest,
  ApiProblem,
  RestockRequest,
  StockResponse,
} from '../models/index';
import {
    AdjustRequestFromJSON,
    AdjustRequestToJSON,
    ApiProblemFromJSON,
    ApiProblemToJSON,
    RestockRequestFromJSON,
    RestockRequestToJSON,
    StockResponseFromJSON,
    StockResponseToJSON,
} from '../models/index';

export interface AdjustOperationRequest {
    productId: number;
    adjustRequest: AdjustRequest;
}

export interface RestockOperationRequest {
    productId: number;
    restockRequest: RestockRequest;
}

/**
 * 
 */
export class AdminInventoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for adjust without sending the request
     */
    async adjustRequestOpts(requestParameters: AdjustOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling adjust().'
            );
        }

        if (requestParameters['adjustRequest'] == null) {
            throw new runtime.RequiredError(
                'adjustRequest',
                'Required parameter "adjustRequest" was null or undefined when calling adjust().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/inventory/products/{productId}/adjust`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdjustRequestToJSON(requestParameters['adjustRequest']),
        };
    }

    /**
     */
    async adjustRaw(requestParameters: AdjustOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockResponse>> {
        const requestOptions = await this.adjustRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockResponseFromJSON(jsonValue));
    }

    /**
     */
    async adjust(requestParameters: AdjustOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockResponse> {
        const response = await this.adjustRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for restock without sending the request
     */
    async restockRequestOpts(requestParameters: RestockOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling restock().'
            );
        }

        if (requestParameters['restockRequest'] == null) {
            throw new runtime.RequiredError(
                'restockRequest',
                'Required parameter "restockRequest" was null or undefined when calling restock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/admin/inventory/products/{productId}/restock`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestockRequestToJSON(requestParameters['restockRequest']),
        };
    }

    /**
     */
    async restockRaw(requestParameters: RestockOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockResponse>> {
        const requestOptions = await this.restockRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockResponseFromJSON(jsonValue));
    }

    /**
     */
    async restock(requestParameters: RestockOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockResponse> {
        const response = await this.restockRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
