CREATE TABLE refunds (
	id BIGINT NOT NULL AUTO_INCREMENT,
	public_id CHAR(36) NOT NULL,
	user_id BIGINT NOT NULL,
	order_id BIGINT NOT NULL,
	payment_intent_id BIGINT NULL,
	status VARCHAR(24) NOT NULL,
	currency CHAR(3) NOT NULL,
	amount DECIMAL(19,2) NOT NULL,
	reason VARCHAR(255) NULL,
	provider VARCHAR(16) NOT NULL,
	provider_reference VARCHAR(128) NULL,
	last_error VARCHAR(2000) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY uk_refunds_public_id (public_id),
	KEY idx_refunds_order (order_id),
	KEY idx_refunds_user (user_id),
	KEY idx_refunds_status (status),
	CONSTRAINT fk_refunds_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
	CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
	CONSTRAINT fk_refunds_pi FOREIGN KEY (payment_intent_id) REFERENCES payment_intents(id) ON DELETE SET NULL
);
