ALTER TABLE auth_sessions
  ADD COLUMN device_name VARCHAR(64) NULL;

ALTER TABLE users
  ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN locked_at TIMESTAMP NULL,
  ADD COLUMN lock_reason VARCHAR(255) NULL;
