/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdjustRequest
 */
export interface AdjustRequest {
    /**
     * 
     * @type {number}
     * @memberof AdjustRequest
     */
    delta: number;
    /**
     * 
     * @type {string}
     * @memberof AdjustRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the AdjustRequest interface.
 */
export function instanceOfAdjustRequest(value: object): value is AdjustRequest {
    if (!('delta' in value) || value['delta'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function AdjustRequestFromJSON(json: any): AdjustRequest {
    return AdjustRequestFromJSONTyped(json, false);
}

export function AdjustRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdjustRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'delta': json['delta'],
        'reason': json['reason'],
    };
}

export function AdjustRequestToJSON(json: any): AdjustRequest {
    return AdjustRequestToJSONTyped(json, false);
}

export function AdjustRequestToJSONTyped(value?: AdjustRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delta': value['delta'],
        'reason': value['reason'],
    };
}

