/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelRequest
 */
export interface CancelRequest {
    /**
     * 
     * @type {string}
     * @memberof CancelRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the CancelRequest interface.
 */
export function instanceOfCancelRequest(value: object): value is CancelRequest {
    return true;
}

export function CancelRequestFromJSON(json: any): CancelRequest {
    return CancelRequestFromJSONTyped(json, false);
}

export function CancelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function CancelRequestToJSON(json: any): CancelRequest {
    return CancelRequestToJSONTyped(json, false);
}

export function CancelRequestToJSONTyped(value?: CancelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

