/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { WebhookEventRow } from './WebhookEventRow';
import {
    WebhookEventRowFromJSON,
    WebhookEventRowFromJSONTyped,
    WebhookEventRowToJSON,
    WebhookEventRowToJSONTyped,
} from './WebhookEventRow';

/**
 * 
 * @export
 * @interface PageResponse
 */
export interface PageResponse {
    /**
     * Listed items
     * @type {Array<WebhookEventRow>}
     * @memberof PageResponse
     */
    items?: Array<WebhookEventRow>;
    /**
     * Paging metadata
     * @type {PageMeta}
     * @memberof PageResponse
     */
    page?: PageMeta;
}

/**
 * Check if a given object implements the PageResponse interface.
 */
export function instanceOfPageResponse(value: object): value is PageResponse {
    return true;
}

export function PageResponseFromJSON(json: any): PageResponse {
    return PageResponseFromJSONTyped(json, false);
}

export function PageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(WebhookEventRowFromJSON)),
        'page': json['page'] == null ? undefined : PageMetaFromJSON(json['page']),
    };
}

export function PageResponseToJSON(json: any): PageResponse {
    return PageResponseToJSONTyped(json, false);
}

export function PageResponseToJSONTyped(value?: PageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(WebhookEventRowToJSON)),
        'page': PageMetaToJSON(value['page']),
    };
}

