/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestockRequest
 */
export interface RestockRequest {
    /**
     * 
     * @type {number}
     * @memberof RestockRequest
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof RestockRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the RestockRequest interface.
 */
export function instanceOfRestockRequest(value: object): value is RestockRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function RestockRequestFromJSON(json: any): RestockRequest {
    return RestockRequestFromJSONTyped(json, false);
}

export function RestockRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestockRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'reason': json['reason'],
    };
}

export function RestockRequestToJSON(json: any): RestockRequest {
    return RestockRequestToJSONTyped(json, false);
}

export function RestockRequestToJSONTyped(value?: RestockRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'reason': value['reason'],
    };
}

