/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipRequest
 */
export interface ShipRequest {
    /**
     * 
     * @type {string}
     * @memberof ShipRequest
     */
    carrier?: string;
    /**
     * 
     * @type {string}
     * @memberof ShipRequest
     */
    trackingNumber?: string;
}

/**
 * Check if a given object implements the ShipRequest interface.
 */
export function instanceOfShipRequest(value: object): value is ShipRequest {
    return true;
}

export function ShipRequestFromJSON(json: any): ShipRequest {
    return ShipRequestFromJSONTyped(json, false);
}

export function ShipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'carrier': json['carrier'] == null ? undefined : json['carrier'],
        'trackingNumber': json['trackingNumber'] == null ? undefined : json['trackingNumber'],
    };
}

export function ShipRequestToJSON(json: any): ShipRequest {
    return ShipRequestToJSONTyped(json, false);
}

export function ShipRequestToJSONTyped(value?: ShipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrier': value['carrier'],
        'trackingNumber': value['trackingNumber'],
    };
}

