/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockResponse
 */
export interface StockResponse {
    /**
     * 
     * @type {number}
     * @memberof StockResponse
     */
    stockQuantity?: number;
}

/**
 * Check if a given object implements the StockResponse interface.
 */
export function instanceOfStockResponse(value: object): value is StockResponse {
    return true;
}

export function StockResponseFromJSON(json: any): StockResponse {
    return StockResponseFromJSONTyped(json, false);
}

export function StockResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
    };
}

export function StockResponseToJSON(json: any): StockResponse {
    return StockResponseToJSONTyped(json, false);
}

export function StockResponseToJSONTyped(value?: StockResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stockQuantity': value['stockQuantity'],
    };
}

