/* tslint:disable */
/* eslint-disable */
/**
 * Pehlione Web API
 * E-commerce backend API (Spring Boot 4)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEventRow
 */
export interface WebhookEventRow {
    /**
     * 
     * @type {string}
     * @memberof WebhookEventRow
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventRow
     */
    payloadHash?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventRow
     */
    provider?: string;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEventRow
     */
    receivedAt?: Date;
}

/**
 * Check if a given object implements the WebhookEventRow interface.
 */
export function instanceOfWebhookEventRow(value: object): value is WebhookEventRow {
    return true;
}

export function WebhookEventRowFromJSON(json: any): WebhookEventRow {
    return WebhookEventRowFromJSONTyped(json, false);
}

export function WebhookEventRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventRow {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'payloadHash': json['payloadHash'] == null ? undefined : json['payloadHash'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'receivedAt': json['receivedAt'] == null ? undefined : (new Date(json['receivedAt'])),
    };
}

export function WebhookEventRowToJSON(json: any): WebhookEventRow {
    return WebhookEventRowToJSONTyped(json, false);
}

export function WebhookEventRowToJSONTyped(value?: WebhookEventRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventId': value['eventId'],
        'payloadHash': value['payloadHash'],
        'provider': value['provider'],
        'receivedAt': value['receivedAt'] == null ? value['receivedAt'] : value['receivedAt'].toISOString(),
    };
}

